#include <linux/limits.h>
#include <linux/math.h>
#include <linux/math64.h>
#include <linux/units.h>

#define OSC_CLK_IN_MEGA		(24 * MEGA)

struct rzg3l_pll_div_limits {
	struct {
		u32 min;
		u32 max;
	} fdco0, fdco1, nr_pow_12;

	struct {
		u8 min;
		u8 max;
	} pr, mr;

	struct {
		u16 min;
		u16 max;
	} nir, nfr;

	struct {
		int min;
		int max;
	} fstd_div_mr;
};

struct rzg3l_plldsi_parameters {
	u64 freq_millihz;
	s64 error_millihz;
	u8 pr, mr;
	u16 nir, nfr;
	u8 rangesel;
	bool is_dsi;
};

static const struct rzg3l_pll_div_limits rzg3l_cpg_pll_dsi_limits = {
	.fdco0 = { .min = 900 * MEGA, .max = 2000 * MEGA },
	.fdco1 = { .min = 2000 * MEGA, .max = 3000 * MEGA },
	.pr = { .min = 0, .max = 4 },
	.mr = { .min = 0, .max = 11 },
	.nir = { .min = 55, .max = 374 },
	.nfr = { .min = 0, .max = 4095 },
	.nr_pow_12 = { .min = 230400, .max = 1536000 },
	.fstd_div_mr = { .min = 8 * MEGA, .max = 16 * MEGA },
};

static __maybe_unused bool
rzg3l_dsi_get_pll_parameters_values(const struct rzg3l_pll_div_limits *limits,
						struct rzg3l_plldsi_parameters *pars,
						u64 freq_millihz)
{
	struct rzg3l_plldsi_parameters p, best;

	/* Initialize best error to maximum possible value */
	best.error_millihz = S64_MAX;

	for (p.mr = limits->mr.min; p.mr <= limits->mr.max; p.mr++) {
		u32 fref = OSC_CLK_IN_MEGA / (p.mr + 1);

		if (fref > limits->fstd_div_mr.max || fref < limits->fstd_div_mr.min)
			continue;

		for (p.pr = limits->pr.min; p.pr <= limits->pr.max; p.pr++) {
			u32 divider = 1 << p.pr;

			for (p.nir = limits->nir.min; p.nir <= limits->nir.max; p.nir++) {
				u64 output_nir, output_nfr_range;
				s64 nfr, output_k;
				u64 fdco, output;

				/*
				 * The frequency generated by the combination of the
				 * PLL + divider is calculated as follows:
				 *
				 * Freq = Ffout / csdiv
				 *
				 * With:
				 * Ffout = Ffdco / 2^(pr)
				 * Ffdco = (nir + (nfr / 4096)) * Ffref
				 * Ffref = 24MHz / mr
				 *
				 * Freq can also be rewritten as:
				 * Freq = Ffdco / (2^(pr) * csdiv))
				 *      = Ffdco / divider
				 *      = (nir * Ffref) / divider + ((nfr / 4096) * Ffref) / divider
				 *      = output_nir + output_nfr
				 *
				 * Every parameter has been determined at this point, but nfr.
				 * Considering that:
				 * 0 <= nfr <= 4095
				 * Then:
				 * 0 <= (nfr / 4096) < 1
				 * Therefore:
				 * 0 <= output_k < Ffref / divider
				 */

				/* Compute output M component (in mHz) */
				output_nir = DIV_ROUND_CLOSEST_ULL((p.nir + 1) * fref * 1000ULL,
								 divider);
				/* Compute range for output K (in mHz) */
				output_nfr_range = DIV_ROUND_CLOSEST_ULL(fref * 1000ULL,
								       divider);
				/*
				 * No point in continuing if we can't achieve the
				 * desired frequency
				 */
				if (freq_millihz < output_nir  ||
				    freq_millihz >= (output_nir + output_nfr_range))
					continue;

				/*
				 * Compute the K component
				 *
				 * Since:
				 * Freq = output_nir + output_k
				 * Then:
				 * output_k = Freq - output_nir
				 *          = ((nfr / 4096) * Ffref) / divider
				 * Therefore:
				 * nfr = (output_k * 4096 * divider) / Ffref
				 */
				output_k = freq_millihz - output_nir;
				nfr = div64_s64(output_k * 4096ULL * divider, fref);
				nfr = DIV_S64_ROUND_CLOSEST(nfr, 1000);

				/* Validate K value within allowed limits */
				if (nfr < limits->nfr.min || nfr > limits->nfr.max)
					continue;

				p.nfr = nfr;

				/* Compute (Ffdco * 4096) */
				fdco = (((p.nir + 1) * 4096ULL) + p.nfr) * fref;
				if ((fdco >= (limits->fdco0.min * 4096ULL)) &&
				    (fdco <= (limits->fdco0.max * 4096ULL)))
					p.rangesel = 0;
				else if ((fdco >= (limits->fdco1.min * 4096ULL)) &&
					(fdco <= (limits->fdco1.max * 4096ULL)))
					p.rangesel = 1;
				else
					continue;

				/* nir component of (output * 4096 * mr) */
				output = (p.nir + 1) * 4096ULL * OSC_CLK_IN_MEGA;
				/* nfr component of (output * 4096 * mr) */
				output += p.nfr * OSC_CLK_IN_MEGA;
				/* Make it in mHz */
				output *= 1000ULL;
				output /= 4096ULL * (p.mr + 1) * divider;

				p.error_millihz = freq_millihz - output;
				p.freq_millihz = output;

				/* If an exact match is found, return immediately */
				if (p.error_millihz == 0) {
					*pars = p;
					return true;
				}

				/* Update best match if error is smaller */
				if (abs(best.error_millihz) > abs(p.error_millihz))
					best = p;
			}
		}
	}

	/* If no valid parameters were found, return false */
	if (best.error_millihz == S64_MAX)
		return false;

	*pars = best;
	return true;

}
