# SPDX-License-Identifier: GPL-2.0-only
#obj-$(CONFIG_CLK_SIFIVE_FU540_PRCI)	+= fu540-prci.o
#obj-$(CONFIG_CLK_SIFIVE_FU740_PRCI)     += fu740-prci.o
obj-$(CONFIG_CLK_SIFIVE_PRCI) += sifive-prci.o fu540-prci.o fu740-prci.o
